version: '3.9'

services:
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"  # Specify ports as a list with the correct format
    volumes:
      - mongodb:/data/db

  api:
    build: .
    ports:
      - 4000:5000
    environment:
      PORT: 5000
      MONGODB_URI: "mongodb://mongodb:27017/user"
    depends_on:
      - mongodb

volumes:
  mongodb: # Define the mongodb volume here
